### ISSUE TITLE
How to repack Ubifs with right metod???

### ISSUE THREAD

**Issue by vuteam** [nlitsme/ubidump#12]
Hello sir i have a box Enigma2 VU+ solo2 and he use Ubifs File System In Their Image

root_cfe_auto.bin  The extract Ubifs Is OK No problem Butwhen i Edit The content Of This Image 

and Repack with Mkfs.ubifs  and I reflash My Box VU+ solo2 the receiver not Start and In the fron On the box stay In  "Starting....."

can you help me for This Sir

thank you

**Comment by nlitsme** [comment]
Sorry, never tried that,  i think you should try the linux-mtd mailinglist.
