### ISSUE TITLE
E: global name 'PermissionError' is not defined

### ISSUE THREAD

**Issue by thriftguy1** [nlitsme/ubidump#25]
ubidump has trouble with this file, as you can see it is a 5 volume ubi the output is the same on more than one pc. I only need the rfs issue solved I have a workaround for the other volumes but not for the rfs

$ ubidump --s ./ systemcut.ubi
==> systemcut.ubi <==
5 named volumes found, 3 physical volumes, blocksize=0x40000
== volume rootfs ==
E: global name 'PermissionError' is not defined
== volume usrfs ==
E: volume does not contain lnum
== volume cachefs ==
E: volume does not contain lnum
== volume systemrw ==
E: volume does not contain lnum
== volume persist ==
E: volume does not contain lnum

If I break it down to ubifs, here is the output 

ubidump --s ./ --debug rootfs.ubifs
==> rootfs.ubifs <==
ERROR global name 'PermissionError' is not defined
Traceback (most recent call last):
  File "/home/bin/ubidump", line 11, in <module>
    sys.exit(main())
  File "/home/lib/python2.7/site-packages/ubidump.py", line 1561, in main
    processfile(fn, args)
  File "/home/lib/python2.7/site-packages/ubidump.py", line 1518, in processfile
    processvolume(RawVolume(fh), b"raw", args)
  File "/home/lib/python2.7/site-packages/ubidump.py", line 1334, in processvolume
    except PermissionError as e:
NameError: global name 'PermissionError' is not defined

any help would be great thank you

**Comment by nlitsme** [comment]
the reason for the " NameError: global name 'PermissionError' is not defined"  message is that you are still using python2, which is very old, I no longer keep my code backward compatible.

So I suggest you install python3.
