### ISSUE TITLE
Directory and File Permissions

### ISSUE THREAD

**Issue by therealjumbo** [nlitsme/ubidump#6]
Is there anyway to preserve the permissions of the directories and files when unpacking them with the `--savedir` option? Like with [fakeroot](https://wiki.debian.org/FakeRoot) or something similar?

**Comment by nlitsme** [comment]
I have added a `-p` option in my latest commit: https://github.com/nlitsme/ubidump/commit/70b491410ac31022265cef4aed22847b81ada3b4

**Comment by therealjumbo** [comment]
Ok, cool. I was wondering about user:group ownership too, although that's obviously a lot more difficult.
